apiVersion: v1
kind: Service
metadata:
  name:  etutor-payment-service
spec:
  selector:
    app: payment-service
  ports:
  - name:  payment-service
    protocol: TCP
    port:  8086
    targetPort: 8086