apiVersion: apps/v1
kind: Deployment
metadata:
  name: etutor-notification-deployment
  labels:
    name:  notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - image: etutor.azurecr.io/etutor-notification:latest
        name: notification-service
        envFrom:
          - configMapRef:
              name: notification-service-config